spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: initializer
  mustache:
    suffix:

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

server:
  port: 8086

initializer:
  template-path: templates/projectCreation