spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: initializer
  mustache:
    suffix:
endpoints:
  enabled: false
  health:
    enabled: true

server:
  port: 8086

initializer:
  template-path: templates/projectCreation