swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8086'
basePath: /
tags:
  - name: component-controller
    description: Component Controller
paths:
  /api/project/generate:
    post:
      tags:
        - component-controller
      summary: userDownload
      operationId: userDownloadUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: component
          description: component
          required: true
          schema:
            $ref: '#/definitions/ProjectProperties'
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: byte
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ProjectProperties:
    type: object
    properties:
      group:
        type: string
      name:
        type: string
      type:
        type: string
        enum:
          - JAVA_SPRING_BOOT
          - JAVA_SPRING_BOOT_2
          - JAVA_LIBRARY
          - NODE
          - REACT
    title: ProjectProperties
